GET http://localhost:9090/auth

PUT http://localhost:9090/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgxNDY5MTIsImlzcyI6InRlc3QifQ.qJ3yCaBqMgb81f3jmpcdBigqAkle56ZerHvy18AC9p4

{
  "task": "new"
}

GET http://localhost:9090/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgxNDY5MTIsImlzcyI6InRlc3QifQ.qJ3yCaBqMgb81f3jmpcdBigqAkle56ZerHvy18AC9p4

PUT http://localhost:9090/todos/0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgxNDY5MTIsImlzcyI6InRlc3QifQ.qJ3yCaBqMgb81f3jmpcdBigqAkle56ZerHvy18AC9p4

GET http://localhost:9090/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgxNDY5MTIsImlzcyI6InRlc3QifQ.qJ3yCaBqMgb81f3jmpcdBigqAkle56ZerHvy18AC9p4
